#
# Palcon Applcition Core
#

# Pull base image
FROM busybox

MAINTAINER Serghei Iakovlev <serghei@phalconphp.com>

RUN mkdir /var/www/phalcon

WORKDIR /var/www/phalcon

# Set up the application directory
VOLUME /var/www/phalcon

CMD /bin/sh
